# ---------------------------------------------------------------------------
# Site metadata
# ---------------------------------------------------------------------------
title: "Bitcoin Conservatory"
title_separator: "-"
description: "Where arbitrary data meets permanence."
url: "https://bitcoinconservatory.com"
repository: "bitcoinconservatory/bitcoinconservatory-dot-com"
baseurl: ""

# ---------------------------------------------------------------------------
# Include directories
# ---------------------------------------------------------------------------
include:
  - "_pages"

# ---------------------------------------------------------------------------
# Collections
# ---------------------------------------------------------------------------
collections:
  lessons:
    output: true
    permalink: /learn/:path/

# ---------------------------------------------------------------------------
# Front Matter defaults
# ---------------------------------------------------------------------------
defaults:
  - scope:
      path: ""
      type: lessons
    values:
      layout: single
      categories: []
